### ISSUE TITLE
How to develop my own configuration and template yaml

### ISSUE THREAD

**Issue by khongks** [marcoantonioni/cp4ba-installations#1]
Could you please provide instructions on how to develop my own configuration and template yaml flie?

Example, I want to install an production ADP file.

**Comment by marcoantonioni** [comment]
Hello khongks,

you can use the examples you find inside the case installation package, see link of versions

https://github.com/IBM/cloud-pak/tree/master/repo/case/ibm-cp-automation


for example in case installation folder

ibm-cp-automation-5.1.5/ibm-cp-automation/inventory/cp4aOperatorSdk/files/deploy/crs/cert-kubernetes/descriptors/patterns

you find the templates for the various capabilities (eg: ibm_cp4a_cr_production_document_processing.yaml), create a copy of the yaml file,
then you modify it by defining the names of the variables that you want to set in the properties pair file.
